export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const DELETE_DATA = 'DELETE_DATA';
export const CHOOSE_ITEM = 'CHOOSE_ITEM';
export const CHANGE_LINE_PROPS = 'CHANGE_LINE_PROPS';
